server:
  port: 8081

spring:
  #MYSQL
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://123.249.98.26:3306/dcloud_account?characterEncoding=utf8&connectTimeout=10000&socketTimeout=30000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xdclass.net

  #  Redis
  data:
    redis:
      database: 0 # Indicate which database on Redis you want to manipulate(??).
      port: 6379      # Redis port is default 6379
      host: localhost
      # Other
      lettuce:
        pool:
          min-idle: 5
          max-idle: 10
          max-active: 8
          max-wait: 1ms
          shutdown-timeout: 100ms

#MybatisPlus
mybatis-plus:
  #  xml文件地址
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # print sql logs.
    map-underscore-to-camel-case: true  # map underscore
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler   # EnumHandler
  global-config:
    db-config:
      id-type: auto  # Global id, if variable id don't have @TableId.
      update-strategy: not_null # Just update not null value.
      # Logic Delete
      logic-delete-field: deleted  # Globally Logic deletion
      logic-delete-value: 1      # Deleted value is 1
      logic-not-delete-value: 0   # Not deleted value is 0

# knife3j
# http://localhost:8080/doc.html
knife4j:
  enable: true
  setting:
    language: zh_cn
  openapi:
    title: UMSDemo
    description: "`I'm Gamer`,**你知道吗**"
    email: 3021809270@qqc.com
    concat: RainbowJier
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/