server:
  port: 9003

spring:
  application:
    name: dcloud-gateway-server
  cloud:
    # Nacos
    nacos:
      discovery:
        enabled: true
        server-addr: 123.249.98.26:8848
        username: nacos
        password: nacos

    # Gateway
    gateway:
      # 开启全局跨域
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      # 自动查找注册在nacos上的服务实例
      discovery:
        locator:
          enabled: true
      routes:
        - id: dcloud-link-api-service
          uri: lb://dcloud-link-service
          order: 1
          predicates:
            - Path=/*

        - id: dcloud-link-service
          uri: lb://dcloud-link-service
          order: 2
          predicates:
            - Path=/link-server/**
          filters:
            - StripPrefix=1

        - id: dcloud-data-service
          uri: lb://dcloud-data-service
          order: 3
          predicates:
            - Path=/data-server/**
          filters:
            - StripPrefix=1

        - id: dcloud-account-service
          uri: lb://dcloud-account-service
          order: 4
          predicates:
            - Path=/account-server/**
          filters:
            - StripPrefix=1

        - id: dcloud-shop-service
          uri: lb://dcloud-shop-service
          order: 5
          predicates:
            - Path=/shop-server/**
          filters:
            - StripPrefix=1