server:
  port: 9003

spring:
  application:
    name: dcloud-gateway-server
  cloud:
    # Nacos
    nacos:
      discovery:
        server-addr: 123.249.98.26:8848
        username: nacos
        enabled: true
        password: nacos

    # Gateway
    gateway:
      routes: #\u914D\u7F6E\u8DEF\u7531, \u53EF\u4EE5\u6709\u591A\u4E2A\u8DEF\u7531\u914D\u7F6E
        - id: dcloud-link-api-service    #\u6570\u636E\u670D\u52A1 \u8DEF\u7531\u552F\u4E00\u6807\u8BC6
          uri: lb://dcloud-link-service  #\u4E00\u822C\u4ECEnacos\u83B7\u53D6\u670D\u52A1\u5730\u5740\uFF0Clb:// \u8868\u793A\u8D1F\u8F7D\u5747\u8861\u5668\uFF08Load Balancer\uFF09\uFF0Cdcloud-link-service\uFF1A\u670D\u52A1\u540D
          order: 1                       #\u4F18\u5148\u7EA7\uFF0C\u6570\u5B57\u8D8A\u2F29\u4F18\u5148\u7EA7\u8D8A\u2FBC
          predicates:
            - Path=/*

        - id: dcloud-link-service
          uri: lb://dcloud-link-service
          order: 2
          predicates:
            - Path=/link-server/**
          # \u8FC7\u6EE4\u5668
          filters:
            - StripPrefix=1  #\u53BB\u6389\u7B2C\u2F00\u5C42\u524D\u7F00\uFF0C/link-server/api/test -> /api/test

        - id: dcloud-data-service
          uri: lb://dcloud-data-service
          order: 3
          predicates:
            - Path=/data-server/**
          filters:
            - StripPrefix=1

        - id: dcloud-account-service
          uri: lb://dcloud-account-service
          order: 4
          predicates:
            - Path=/account-server/**
          filters:
            - StripPrefix=1

        - id: dcloud-shop-service
          uri: lb://dcloud-shop-service
          order: 5
          predicates:
            - Path=/shop-server/**
          filters:
            - StripPrefix=1


